AppView/Controllers/GGsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppData;

namespace AppView.Controllers
{
    public class GGsController : Controller
    {
        private readonly HotelDbContext _context;

        public GGsController(HotelDbContext context)
        {
            _context = context;
        }

        // GET: GGs
        public async Task<IActionResult> Index()
        {
            return PartialView(await _context.gGs.ToListAsync());
        }

        // GET: GGs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gG = await _context.gGs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gG == null)
            {
                return NotFound();
            }

            return PartialView(gG);
        }

        // GET: GGs/Create
        public IActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]

        public async Task<IActionResult> Create([Bind("Id,Link,Hinh,TrangThai")] GG gG, IFormFile imageFile)
        {

            if (!ModelState.IsValid)
            {
                if (imageFile != null && imageFile.Length > 0)
                {
                    // Lưu file vào thư mục trên server
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/icon", imageFile.FileName);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await imageFile.CopyToAsync(stream);
                    }

                    // Lưu đường dẫn file vào database
                    gG.Hinh = imageFile.FileName;
                }

                _context.Add(gG);  // Thêm đối tượng DichVu vào CSDL
                _context.SaveChanges();  // Lưu thay đổi vào CSDL
                return RedirectToAction(nameof(Index));  // Điều hướng về trang danh sách
            }

            return View(gG);
        }

        // GET: FaceBooks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gg = await _context.gGs.FindAsync(id);
            if (gg == null)
            {
                return NotFound();
            }
            return PartialView(gg);
        }


        [HttpPost]

        public async Task<IActionResult> Edit(int id, [Bind("Id,Hinh,Link,TrangThai")] GG gG, IFormFile imageFile)
        {
            if (id != gG.Id)
            {
                return NotFound();
            }


            if (!ModelState.IsValid)
            {
                if (imageFile != null && imageFile.Length > 0)
                {
                    // Lưu file vào thư mục trên server
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", imageFile.FileName);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await imageFile.CopyToAsync(stream);
                    }

                    // Lưu đường dẫn file vào database
                    gG.Hinh = imageFile.FileName;
                }
                _context.Update(gG);  // Thêm đối tượng DichVu vào CSDL
                _context.SaveChanges();  // Lưu thay đổi vào CSDL
                return RedirectToAction(nameof(Index));  // Điều hướng về trang danh sách
            }

            return View(gG);
        }

        // GET: GGs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gG = await _context.gGs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gG == null)
            {
                return NotFound();
            }

            return View(gG);
        }

        // POST: GGs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gG = await _context.gGs.FindAsync(id);
            if (gG != null)
            {
                _context.gGs.Remove(gG);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GGExists(int id)
        {
            return _context.gGs.Any(e => e.Id == id);
        }
    }
}

AppView/Controllers/IntersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppData;

namespace AppView.Controllers
{
    public class IntersController : Controller
    {
        private readonly HotelDbContext _context;

        public IntersController(HotelDbContext context)
        {
            _context = context;
        }

        // GET: Inters
        public async Task<IActionResult> Index()
        {
            return PartialView(await _context.inters.ToListAsync());
        }

        // GET: Inters/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inter = await _context.inters
                .FirstOrDefaultAsync(m => m.Id == id);
            if (inter == null)
            {
                return NotFound();
            }

            return PartialView(inter);
        }

        // GET: Inters/Create
        public IActionResult Create()
        {
            return PartialView();
        }
        [HttpPost]

        public async Task<IActionResult> Create([Bind("Id,Link,Hinh,TrangThai")] Inter gG, IFormFile imageFile)
        {

            if (!ModelState.IsValid)
            {
                if (imageFile != null && imageFile.Length > 0)
                {
                    // Lưu file vào thư mục trên server
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/icon", imageFile.FileName);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await imageFile.CopyToAsync(stream);
                    }

                    // Lưu đường dẫn file vào database
                    gG.Hinh = imageFile.FileName;
                }

                _context.Add(gG);  // Thêm đối tượng DichVu vào CSDL
                _context.SaveChanges();  // Lưu thay đổi vào CSDL
                return RedirectToAction(nameof(Index));  // Điều hướng về trang danh sách
            }

            return View(gG);
        }

        // GET: FaceBooks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gg = await _context.inters.FindAsync(id);
            if (gg == null)
            {
                return NotFound();
            }
            return PartialView(gg);
        }


        [HttpPost]

        public async Task<IActionResult> Edit(int id, [Bind("Id,Hinh,Link,TrangThai")] Inter gG, IFormFile imageFile)
        {
            if (id != gG.Id)
            {
                return NotFound();
            }


            if (!ModelState.IsValid)
            {
                if (imageFile != null && imageFile.Length > 0)
                {
                    // Lưu file vào thư mục trên server
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", imageFile.FileName);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await imageFile.CopyToAsync(stream);
                    }

                    // Lưu đường dẫn file vào database
                    gG.Hinh = imageFile.FileName;
                }
                _context.Update(gG);  // Thêm đối tượng DichVu vào CSDL
                _context.SaveChanges();  // Lưu thay đổi vào CSDL
                return RedirectToAction(nameof(Index));  // Điều hướng về trang danh sách
            }

            return View(gG);
        }

        // GET: Inters/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inter = await _context.inters
                .FirstOrDefaultAsync(m => m.Id == id);
            if (inter == null)
            {
                return NotFound();
            }

            return View(inter);
        }

        // POST: Inters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var inter = await _context.inters.FindAsync(id);
            if (inter != null)
            {
                _context.inters.Remove(inter);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InterExists(int id)
        {
            return _context.inters.Any(e => e.Id == id);
        }
    }
}

AppView/Controllers/LoGoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppData;
using AppView.ViewModels;

namespace AppView.Controllers
{
    public class LoGoesController : Controller
    {
        private readonly HotelDbContext _context;

        public LoGoesController(HotelDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return PartialView(_context.loGos.ToList());
        }

        // GET: LoGo/Create
        public IActionResult Create()
        {
            return PartialView();
        }

        // POST: LoGo/Create
        [HttpPost]
        
        public async Task<IActionResult> Create([Bind("ID,Logo,TrangThai")]  LoGo logo, IFormFile imageFile)
        {
            
            /*if (!ModelState.IsValid)*/
            {
            if (imageFile != null && imageFile.Length > 0)
                {
                    // Lưu file vào thư mục trên server
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", imageFile.FileName);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await imageFile.CopyToAsync(stream);
                    }

                    // Lưu đường dẫn file vào database
                    logo.Logo = imageFile.FileName;
                }

                _context.Add(logo);  // Thêm đối tượng DichVu vào CSDL
                _context.SaveChanges();  // Lưu thay đổi vào CSDL
                return RedirectToAction(nameof(Index));  // Điều hướng về trang danh sách
            }

            return View(logo);
        }

        //// GET: LoGoes/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var loGo = await _context.loGos
        //        .FirstOrDefaultAsync(m => m.ID == id);
        //    if (loGo == null)
        //    {
        //        return NotFound();
        //    }

        //    return PartialView(loGo);
        //}

      
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dichVu = await _context.loGos.FindAsync(id);
            if (dichVu == null)
            {
                return NotFound();
            }
            return PartialView(dichVu);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, LoGo logo, IFormFile imageFile)
        {
            if (id != logo.ID)
            {
                return NotFound();
            }

           /* if (!ModelState.IsValid)*/
            {
                if (imageFile != null && imageFile.Length > 0)
                {
                    // Lưu file vào thư mục trên server
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", imageFile.FileName);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await imageFile.CopyToAsync(stream);
                    }

                    // Lưu đường dẫn file vào database
                    logo.Logo = imageFile.FileName;
                }
                _context.Update(logo);  // Thêm đối tượng DichVu vào CSDL
                _context.SaveChanges();  // Lưu thay đổi vào CSDL
                return RedirectToAction(nameof(Index));  // Điều hướng về trang danh sách
            }

              
            
            return View(logo);
        }

        // GET: LoGoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loGo = await _context.loGos
                .FirstOrDefaultAsync(m => m.ID == id);
            if (loGo == null)
            {
                return NotFound();
            }

            return View(loGo);
        }

        // POST: LoGoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var loGo = await _context.loGos.FindAsync(id);
            if (loGo != null)
            {
                _context.loGos.Remove(loGo);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LoGoExists(int id)
        {
            return _context.loGos.Any(e => e.ID == id);
        }
    }
}

AppView/Views/TaiKhoan/Create.cshtml
@model AppData.TaiKhoann

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TaiKhoann</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TaiKhoan" class="control-label"></label>
                <input asp-for="TaiKhoan" class="form-control" />
                <span asp-validation-for="TaiKhoan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MatKhau" class="control-label"></label>
                <input asp-for="MatKhau" class="form-control" />
                <span asp-validation-for="MatKhau" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="TrangQuanLy" asp-controller="TaiKhoan">Back</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppView/Views/TaiKhoan/DangNhap.cshtml
@* @{
    ViewData["Title"] = "Đăng Nhập";
}

<h2>Đăng Nhập</h2>

<form asp-action="DangNhap" method="post" class="container">
    <div class="form-group">
        <label for="TaiKhoan">Tài khoản:</label>
        <input type="text" class="form-control" id="TaiKhoan" name="TaiKhoan" required>
    </div>
    <div class="form-group">
        <label for="MatKhau">Mật khẩu:</label>
        <input type="password" class="form-control" id="MatKhau" name="MatKhau" required>
    </div>
    <button type="submit" class="btn btn-primary">Đăng Nhập</button>
</form>

@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger mt-3">
        @ViewBag.ErrorMessage
    </div>
}


 *@


@{
    ViewData["Title"] = "Đăng Nhập";
}

<div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <div class="card shadow-lg" style="width: 100%; max-width: 400px;">
        <div class="card-body">
            <h2 class="text-center">@ViewData["Title"]</h2>
            <hr />
            <form asp-action="DangNhap" method="post">
                @if (ViewBag.ErrorMessage != null)
                {
                    <div class="alert alert-danger text-center">
                        @ViewBag.ErrorMessage
                    </div>
                }

                <div class="mb-3">
                    <label for="TaiKhoan" class="form-label">Tài khoản</label>
                    <div class="input-group">
                        <span class="input-group-text"><i class="bi bi-person"></i></span>
                        <input type="text" class="form-control" id="TaiKhoan" name="TaiKhoan" placeholder="Nhập tài khoản" required>
                    </div>
                </div>

                <div class="mb-3">
                    <label for="MatKhau" class="form-label">Mật khẩu</label>
                    <div class="input-group">
                        <span class="input-group-text"><i class="bi bi-lock"></i></span>
                        <input type="password" class="form-control" id="MatKhau" name="MatKhau" placeholder="Nhập mật khẩu" required>
                    </div>
                </div>

                <div class="d-grid">
                    <button type="submit" class="btn btn-primary btn-block">Đăng Nhập</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.js"></script>
}

AppView/Views/TaiKhoan/Delete.cshtml
@model AppData.TaiKhoann

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TaiKhoann</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TaiKhoan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TaiKhoan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MatKhau)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MatKhau)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="TrangQuanLy" asp-controller="TaiKhoan">Back</a>
    </form>
</div>

AppView/Views/TaiKhoan/Details.cshtml
@model AppData.TaiKhoann

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TaiKhoann</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TaiKhoan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TaiKhoan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MatKhau)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MatKhau)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="TrangQuanLy" asp-controller="TaiKhoan">Back</a>
</div>

AppView/Views/TaiKhoan/Edit.cshtml
@model AppData.TaiKhoann

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TaiKhoann</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="TaiKhoan" class="control-label"></label>
                <input asp-for="TaiKhoan" class="form-control" />
                <span asp-validation-for="TaiKhoan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MatKhau" class="control-label"></label>
                <input asp-for="MatKhau" class="form-control" />
                <span asp-validation-for="MatKhau" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="TrangQuanLy" asp-controller="TaiKhoan">Back</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppView/Views/TaiKhoan/Index.cshtml
@model IEnumerable<AppData.TaiKhoann>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TaiKhoan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MatKhau)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TaiKhoan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MatKhau)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

AppView/Views/TaiKhoan/TrangQuanLy.cshtml
@{
	ViewData["Title"] = "Trang Quản Lý";
}

<div style="margin-top: 100px;">
	<h2 class="text-center">Chào mừng bạn đến với Trang Quản Lý!</h2>

	<div class="row">
		<div class=" fw-bold btn-group-vertical col-sm-3" role="group" aria-label="Vertical button group">
			<a asp-action="Index" asp-controller="LoGoes" data-ajax="true" class="btn btn-warning">Logo</a>
			<a asp-action="Index" asp-controller="LienHes" data-ajax="true" class="btn btn-warning">SĐT Liên Hệ</a>
			<a asp-action="Index" asp-controller="MenuItems" data-ajax="true" class="btn btn-warning">Menu</a>
			<a asp-action="Index" asp-controller="Slides" data-ajax="true" class="btn btn-warning">Slide</a>
			<a asp-action="Index" asp-controller="WelComes" data-ajax="true" class="btn btn-warning">Lời Chào</a>
			<a asp-action="Index" asp-controller="DichVus" data-ajax="true" class="btn btn-warning">Dịch Vụ</a>
			<a asp-action="Index" asp-controller="LoaiPhongs" data-ajax="true" class="btn btn-warning">Loại Phòng</a>
			<a asp-action="Index" asp-controller="LoaiPhongDichVus" data-ajax="true" class="btn btn-warning">Loại Phòng Dịch Vụ</a>
			<a asp-action="Index" asp-controller="AnhChiTiets" data-ajax="true" class="btn btn-warning">Ảnh Chi Tiết</a>
			<a asp-action="Index" asp-controller="TinTucs" data-ajax="true" class="btn btn-warning">Tin Tức</a>
			
			<a href="/TaiKhoan/Index" data-ajax="true" class="btn btn-warning">Tài Khoản</a>

			<a asp-action="Index" asp-controller="FaceBooks" data-ajax="true" class="btn btn-warning">FB</a>
			<a asp-action="Index" asp-controller="GGs" data-ajax="true" class="btn btn-warning">Google</a>
			<a asp-action="Index" asp-controller="TikToks" data-ajax="true" class="btn btn-warning">Tik Tok</a>
			<a asp-action="Index" asp-controller="Inters" data-ajax="true" class="btn btn-warning">Instagram</a>
		</div>
		<div class="col-sm-9 container" id="content-container">
			
			@* @Html.Partial("_IndexTaiKhoanPartial") *@

		</div>
	</div>

</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
		$(document).ready(function () {
		$("a[data-ajax='true']").on("click", function (e) {
			e.preventDefault(); 

			var url = $(this).attr("href"); 

			
			$.get(url)
				.done(function (data) {
					$("#content-container").html(data); 
				})
				.fail(function () {
					$("#content-container").html('<div class="alert alert-danger">Đã xảy ra lỗi, vui lòng thử lại.</div>');
				});
		});
	});

</script>

AppView/Views/TaiKhoan/_CreateTaiKhoanPartial.cshtml
@model AppData.TaiKhoann

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TaiKhoann</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TaiKhoan" class="control-label"></label>
                <input asp-for="TaiKhoan" class="form-control" />
                <span asp-validation-for="TaiKhoan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MatKhau" class="control-label"></label>
                <input asp-for="MatKhau" class="form-control" />
                <span asp-validation-for="MatKhau" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="TrangQuanLy" asp-controller="TaiKhoan">Back</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

AppView/Views/TaiKhoan/_IndexTaiKhoanPartial.cshtml
@model IEnumerable<AppData.TaiKhoann>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TaiKhoan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MatKhau)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>        
                    @Html.DisplayFor(modelItem => item.TaiKhoan)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MatKhau)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>