AppView/Controllers/TinTucsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppData;

namespace AppView.Controllers
{
    public class TinTucsController : Controller
    {
        private readonly HotelDbContext _context;

        public TinTucsController(HotelDbContext context)
        {
            _context = context;
        }

		public async Task<IActionResult> MyView()
		{
			return View(await _context.tinTucs.ToListAsync());

		}
		public async Task<IActionResult> XemThem(int id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var tinTuc = await _context.tinTucs
				.FirstOrDefaultAsync(m => m.ID == id);
			if (tinTuc == null)
			{
				return NotFound();
			}

			return View(tinTuc);
		}

		// GET: TinTucs
		public async Task<IActionResult> Index()
        {
            return PartialView(await _context.tinTucs.ToListAsync());
        }

        // GET: TinTucs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tinTuc = await _context.tinTucs
                .FirstOrDefaultAsync(m => m.ID == id);
            if (tinTuc == null)
            {
                return NotFound();
            }

            return PartialView(tinTuc);
        }

        // GET: TinTucs/Create
        public IActionResult Create()
        {
            return PartialView();
        }

        // POST: TinTucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,TenTinTucChinh,TenTinTucPhu,HinhAnh1,HinhAnh2,HinhAnh3,NoiDungNgan,NoiDungChiTiet1,NoiDungChiTiet2,NoiDungChiTiet3,NoiDungChiTiet4,TrangThai")] TinTuc tinTuc, IFormFile hinhanh1, IFormFile hinhanh2, IFormFile hinhanh3 )
        {
            if (ModelState.IsValid)
            {
				if (hinhanh1 != null && hinhanh1.Length > 0)
				{
					// Lưu file vào thư mục trên server
					var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/about", hinhanh1.FileName);
					using (var stream = new FileStream(filePath, FileMode.Create))
					{
						await hinhanh1.CopyToAsync(stream);
					}
					// Lưu đường dẫn file vào database
					tinTuc.HinhAnh1 = hinhanh1.FileName;
				}

				if (hinhanh2 != null && hinhanh2.Length > 0)
				{
					// Lưu file vào thư mục trên server
					var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/about", hinhanh2.FileName);
					using (var stream = new FileStream(filePath, FileMode.Create))
					{
						await hinhanh2.CopyToAsync(stream);
					}
					// Lưu đường dẫn file vào database
					tinTuc.HinhAnh2 = hinhanh2.FileName;
				}

				if (hinhanh3 != null && hinhanh3.Length > 0)
				{
					// Lưu file vào thư mục trên server
					var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/about", hinhanh3.FileName);
					using (var stream = new FileStream(filePath, FileMode.Create))
					{
						await hinhanh3.CopyToAsync(stream);
					}
					// Lưu đường dẫn file vào database
					tinTuc.HinhAnh3 = hinhanh3.FileName;
				}

				_context.Add(tinTuc);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tinTuc);
        }

        // GET: TinTucs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tinTuc = await _context.tinTucs.FindAsync(id);
            if (tinTuc == null)
            {
                return NotFound();
            }
            return PartialView(tinTuc);
        }

        // POST: TinTucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,TenTinTucChinh,TenTinTucPhu,HinhAnh1,HinhAnh2,HinhAnh3,NoiDungNgan,NoiDungChiTiet1,NoiDungChiTiet2,NoiDungChiTiet3,NoiDungChiTiet4,TrangThai")] TinTuc tinTuc)
        {
            if (id != tinTuc.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tinTuc);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TinTucExists(tinTuc.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tinTuc);
        }

        // GET: TinTucs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tinTuc = await _context.tinTucs
                .FirstOrDefaultAsync(m => m.ID == id);
            if (tinTuc == null)
            {
                return NotFound();
            }

            return View(tinTuc);
        }

        // POST: TinTucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tinTuc = await _context.tinTucs.FindAsync(id);
            if (tinTuc != null)
            {
                _context.tinTucs.Remove(tinTuc);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TinTucExists(int id)
        {
            return _context.tinTucs.Any(e => e.ID == id);
        }
    }
}

AppView/Views/TinTucs/Create.cshtml
@model AppData.TinTuc

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TinTuc</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TenTinTucChinh" class="control-label"></label>
                <input asp-for="TenTinTucChinh" class="form-control" />
                <span asp-validation-for="TenTinTucChinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenTinTucPhu" class="control-label"></label>
                <input asp-for="TenTinTucPhu" class="form-control" />
                <span asp-validation-for="TenTinTucPhu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HinhAnh1" class="control-label"></label>
                <input type="file" asp-for="HinhAnh1" class="form-control" />
                <span asp-validation-for="HinhAnh1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HinhAnh2" class="control-label"></label>
                <input type="file" asp-for="HinhAnh2" class="form-control" />
                <span asp-validation-for="HinhAnh2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HinhAnh3" class="control-label"></label>
                <input type="file" asp-for="HinhAnh3" class="form-control" />
                <span asp-validation-for="HinhAnh3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoiDungNgan" class="control-label"></label>
                <input asp-for="NoiDungNgan" class="form-control" />
                <span asp-validation-for="NoiDungNgan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoiDungChiTiet1" class="control-label"></label>
                <input asp-for="NoiDungChiTiet1" class="form-control" />
                <span asp-validation-for="NoiDungChiTiet1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoiDungChiTiet2" class="control-label"></label>
                <input asp-for="NoiDungChiTiet2" class="form-control" />
                <span asp-validation-for="NoiDungChiTiet2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoiDungChiTiet3" class="control-label"></label>
                <input asp-for="NoiDungChiTiet3" class="form-control" />
                <span asp-validation-for="NoiDungChiTiet3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoiDungChiTiet4" class="control-label"></label>
                <input asp-for="NoiDungChiTiet4" class="form-control" />
                <span asp-validation-for="NoiDungChiTiet4" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="TrangThai" /> @Html.DisplayNameFor(model => model.TrangThai)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="TrangQuanLy" asp-controller="TaiKhoan">Back</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppView/Views/TinTucs/Delete.cshtml
@model AppData.TinTuc

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TinTuc</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenTinTucChinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenTinTucChinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenTinTucPhu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenTinTucPhu)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HinhAnh1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HinhAnh1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HinhAnh2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HinhAnh2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HinhAnh3)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HinhAnh3)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoiDungNgan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoiDungNgan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoiDungChiTiet1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoiDungChiTiet1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoiDungChiTiet2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoiDungChiTiet2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoiDungChiTiet3)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoiDungChiTiet3)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoiDungChiTiet4)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoiDungChiTiet4)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrangThai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrangThai)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="TrangQuanLy" asp-controller="TaiKhoan">Back</a>
    </form>
</div>

AppView/Views/TinTucs/Details.cshtml
@model AppData.TinTuc

@{
	ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
	<h4>TinTuc</h4>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.TenTinTucChinh)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.TenTinTucChinh)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.TenTinTucPhu)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.TenTinTucPhu)
		</dd>
		@* <dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.HinhAnh1)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.HinhAnh1)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.HinhAnh2)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.HinhAnh2)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.HinhAnh3)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.HinhAnh3)
		</dd> *@
		<dd class="col-sm-10">
			@if (!string.IsNullOrEmpty(Model.HinhAnh1))
			{
				<img src="~/img/about/@Model.HinhAnh1" alt="Image 1" class="img-fluid" />
			}
			else
			{
				<p>No image available</p>
			}
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.HinhAnh2)
		</dt>
		<dd class="col-sm-10">
			@if (!string.IsNullOrEmpty(Model.HinhAnh2))
			{
				<img src="~/img/about/@Model.HinhAnh2" alt="Image 2" class="img-fluid" />
			}
			else
			{
				<p>No image available</p>
			}
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.HinhAnh3)
		</dt>
		<dd class="col-sm-10">
			@if (!string.IsNullOrEmpty(Model.HinhAnh3))
			{
				<img src="~/img/about/@Model.HinhAnh3" alt="Image 3" class="img-fluid" />
			}
			else
			{
				<p>No image available</p>
			}
		</dd>

		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.NoiDungNgan)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.NoiDungNgan)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.NoiDungChiTiet1)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.NoiDungChiTiet1)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.NoiDungChiTiet2)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.NoiDungChiTiet2)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.NoiDungChiTiet3)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.NoiDungChiTiet3)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.NoiDungChiTiet4)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.NoiDungChiTiet4)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.TrangThai)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.TrangThai)
		</dd>
	</dl>
</div>
<div>
	<a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
	<a asp-action="TrangQuanLy" asp-controller="TaiKhoan">Back</a>
</div>

AppView/Views/TinTucs/Edit.cshtml
@model AppData.TinTuc

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TinTuc</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="TenTinTucChinh" class="control-label"></label>
                <input asp-for="TenTinTucChinh" class="form-control" />
                <span asp-validation-for="TenTinTucChinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenTinTucPhu" class="control-label"></label>
                <input asp-for="TenTinTucPhu" class="form-control" />
                <span asp-validation-for="TenTinTucPhu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HinhAnh1" class="control-label"></label>
                <input asp-for="HinhAnh1" class="form-control" />
                <span asp-validation-for="HinhAnh1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HinhAnh2" class="control-label"></label>
                <input asp-for="HinhAnh2" class="form-control" />
                <span asp-validation-for="HinhAnh2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HinhAnh3" class="control-label"></label>
                <input asp-for="HinhAnh3" class="form-control" />
                <span asp-validation-for="HinhAnh3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoiDungNgan" class="control-label"></label>
                <input asp-for="NoiDungNgan" class="form-control" />
                <span asp-validation-for="NoiDungNgan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoiDungChiTiet1" class="control-label"></label>
                <input asp-for="NoiDungChiTiet1" class="form-control" />
                <span asp-validation-for="NoiDungChiTiet1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoiDungChiTiet2" class="control-label"></label>
                <input asp-for="NoiDungChiTiet2" class="form-control" />
                <span asp-validation-for="NoiDungChiTiet2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoiDungChiTiet3" class="control-label"></label>
                <input asp-for="NoiDungChiTiet3" class="form-control" />
                <span asp-validation-for="NoiDungChiTiet3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoiDungChiTiet4" class="control-label"></label>
                <input asp-for="NoiDungChiTiet4" class="form-control" />
                <span asp-validation-for="NoiDungChiTiet4" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="TrangThai" /> @Html.DisplayNameFor(model => model.TrangThai)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="TrangQuanLy" asp-controller="TaiKhoan">Back</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppView/Views/TinTucs/Index.cshtml
@model IEnumerable<AppData.TinTuc>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TenTinTucChinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TenTinTucPhu)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HinhAnh1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HinhAnh2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HinhAnh3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NoiDungNgan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NoiDungChiTiet1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NoiDungChiTiet2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NoiDungChiTiet3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NoiDungChiTiet4)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TrangThai)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenTinTucChinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenTinTucPhu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HinhAnh1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HinhAnh2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HinhAnh3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoiDungNgan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoiDungChiTiet1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoiDungChiTiet2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoiDungChiTiet3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoiDungChiTiet4)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TrangThai)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

AppView/Views/TinTucs/MyView.cshtml
@model IEnumerable<AppData.TinTuc>
<!-- About Section Start -->
<div id="about">
    <div class="container">
        @foreach (var item in Model)
        {
            @if (item.TrangThai)
            {
                <div class="row" style="margin-bottom: 20px; margin-top:50px">
                    <div class="col-md-6 img-cols">
                        <div class="img-col">
                            <img class="img-fluid w-100" src="~/img/about/@item.HinhAnh1">
                        </div>
                    </div>
                    <div class="col-md-6 content-cols">
                        <div class="content-col">
                            <h3>@item.TenTinTucChinh</h3>
                            <p>
                                @item.NoiDungNgan
                            </p>
                            <a asp-controller="TinTucs" asp-action="XemThem" asp-route-id="@item.ID" class="btn btn-primary">XemThem</a>

                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>

AppView/Views/TinTucs/XemThem.cshtml
@model AppData.TinTuc
<div id="learn-more-section" class="container" style="margin-top:100px">

	@* @if (Model != null && Model.Any())
	{ *@
		@* @foreach (var item in Model)
		{ *@
			@* <h1 class="text-center my-4">@Model.TenTinTucChinh</h1>

			<div class="row mb-4 align-items-center">
				<div class="col-md-3">
					<img src="@Url.Content("~/img/about/" + Model.HinhAnh1)" alt="About Us Image" class="img-fluid rounded">
				</div>

				<div class="col-md-6">
					<p>@Model.NoiDungChiTiet1</p>
				</div>
			</div> *@
		@* } *@
	@* } *@
	@* else
	{
		<p class="text-center">No content available.</p>
	} *@

    <!-- About Section Start -->
    <div id="more-about">
        <div class="container">
            <div class="section-header">
            </div>
            <h2>@Model.TenTinTucChinh</h2>
            <hr>
            <div class="row">
                <div class="col-md-12">
                    <!-- Hình ảnh và đoạn văn bản -->
                    <div class="content-wrapper">
                        <img class="img-left" src="@Url.Content("~/img/about/" + Model.HinhAnh1)" alt="About Image">
                        <p class="text-about">
                            @Model.NoiDungChiTiet1
                            <br><br>
                            @Model.NoiDungChiTiet2
                        </p>

                        <h4>@Model.TenTinTucPhu</h4>
                        <p class="text-about">
                            @Model.NoiDungChiTiet3
                            <br>
                        </p>
                        <div class="row">
                            <div class="col-md-6">
                                <img id="anh" src="@Url.Content("~/img/about/" + Model.HinhAnh2)" alt="">
                            </div>
                            <div class="col-md-6">
                                <img id="anh" src="@Url.Content("~/img/about/" + Model.HinhAnh3)" alt="">
                            </div>
                        </div>
                        <p class="text-about">
                            @Model.NoiDungChiTiet4
                            <br>
                        </p>

                    </div>

                </div>
            </div>
        </div>


    </div>
    <!-- About Section End -->

    <style>
        .text-about {
            text-align: justify; /* Căn đều văn bản */
            font-size: 16px; /* Cỡ chữ */
            line-height: 1.6; /* Độ cao dòng */
        }
        #anh{
            max-width: 100%;
        }
    </style>

</div>